"""
Kie AI Nano Banana 2 ile LinkedIn post görseli üretme.
Eski Gemini pipeline'ı → Kie AI asenkron görev modeline geçirildi.

Pipeline:
  1. GPT-4.1-mini ile görsel prompt üret (İngilizce)
  2. Kie AI Nano Banana 2 ile 16:9 görsel üret (LinkedIn post formatı)
  3. Asenkron polling ile sonucu bekle
  4. Üretilen görseli indir → geçici dosya yolunu döndür
"""
from ops_logger import get_ops_logger
ops = get_ops_logger("LinkedIn_Text_Paylasim", "ImageGenerator")
import requests
import os
import time
import json
import tempfile

from openai import OpenAI
from config import settings


class ImageGenerator:
    """İki aşamalı görsel pipeline: prompt üretme (GPT) + görsel üretme (Kie AI NB2)."""

    KIE_BASE_URL = "https://api.kie.ai/api/v1"
    POLL_INTERVAL = 15  # saniye
    MAX_POLLS = 40  # ~10 dakika max bekleme

    def __init__(self):
        self.openai_client = OpenAI(api_key=settings.OPENAI_API_KEY)
        self.kie_api_key = settings.KIE_API_KEY

    def generate_post_image(self, linkedin_post: str) -> str:
        """
        LinkedIn postu için görsel üretir.
        1. GPT-4.1-mini ile İngilizce görsel prompt yazar
        2. Kie AI Nano Banana 2 ile görseli üretir
        3. Geçici dosya yolunu döndürür

        Returns: Üretilen görselin dosya yolu (str) veya None
        """
        # Adım 1: Görsel prompt üret
        image_prompt = self._generate_image_prompt(linkedin_post)
        if not image_prompt:
            return None

        # Adım 2: Kie AI ile görsel üret
        image_path = self._generate_image_with_kie(image_prompt)
        return image_path

    def _generate_image_prompt(self, linkedin_post: str) -> str:
        """
        GPT-4.1-mini ile İngilizce görsel prompt üretir.
        Nano Banana 2 modeli için optimize edilmiş prompt.
        """
        if settings.IS_DRY_RUN:
            ops.info("[DRY-RUN] Görsel prompt üretme atlanıyor.")
            return "[DRY-RUN] Minimalist AI infographic prompt"

        user_message = (
            "I need you to write an image generation prompt for a LinkedIn post visual. "
            "The image will be generated by an advanced AI model (Nano Banana 2).\n\n"
            "Rules:\n"
            "- Write the prompt in English\n"
            "- Create a clean, professional, minimalist design\n"
            "- Focus on key highlights from the post content\n"
            "- Use modern abstract/tech aesthetics (gradients, geometric shapes, tech elements)\n"
            "- NO text/writing on the image — purely visual\n"
            "- Make it LinkedIn-appropriate (professional, sleek)\n"
            "- Use a 16:9 aspect ratio composition\n"
            "- Only output the prompt, nothing else\n\n"
            f"LINKEDIN POST:\n{linkedin_post}"
        )

        try:
            response = self.openai_client.chat.completions.create(
                model="gpt-4.1-mini",
                messages=[
                    {"role": "user", "content": user_message}
                ],
                temperature=0.7
            )
            prompt = response.choices[0].message.content.strip()
            ops.info(f"Görsel prompt üretildi ({len(prompt)} karakter)")
            return prompt
        except Exception as e:
            ops.error(f"GPT-4.1-mini görsel prompt hatası: {e}", exception=e)
            return None

    def _generate_image_with_kie(self, prompt: str) -> str:
        """
        Kie AI Nano Banana 2 ile görsel üretir.
        Asenkron görev modeli: createTask → polling → download.

        Returns: Üretilen görselin geçici dosya yolu veya None
        """
        if settings.IS_DRY_RUN:
            ops.info("[DRY-RUN] Kie AI görsel üretme atlanıyor.")
            return None

        headers = {
            "Authorization": f"Bearer {self.kie_api_key}",
            "Content-Type": "application/json"
        }

        # Step 1: Görev oluştur
        create_url = f"{self.KIE_BASE_URL}/jobs/createTask"
        payload = {
            "model": "nano-banana-2",
            "input": {
                "prompt": prompt,
                "aspect_ratio": "16:9",
                "resolution": "2k"
            }
        }

        try:
            resp = requests.post(create_url, headers=headers, json=payload, timeout=30)
            resp.raise_for_status()
            data = resp.json()

            if data.get("code") != 200:
                ops.error(f"Kie AI görev oluşturma hatası: {data}")
                return None

            task_id = data.get("data", {}).get("taskId")
            if not task_id:
                ops.error(f"Kie AI yanıtında taskId bulunamadı: {data}")
                return None

            ops.info(f"Kie AI görsel görevi oluşturuldu — taskId: {task_id}")

        except Exception as e:
            ops.error(f"Kie AI görev oluşturma hatası: {e}", exception=e)
            return None

        # Step 2: Polling — sonucu bekle
        poll_url = f"{self.KIE_BASE_URL}/jobs/recordInfo"
        image_url = None

        for attempt in range(1, self.MAX_POLLS + 1):
            time.sleep(self.POLL_INTERVAL)
            try:
                poll_resp = requests.get(
                    poll_url,
                    headers=headers,
                    params={"taskId": task_id},
                    timeout=15
                )
                poll_resp.raise_for_status()
                poll_data = poll_resp.json()

                record = poll_data.get("data", {})
                state = record.get("state", "unknown")

                if state in ("processing", "waiting"):
                    if attempt % 4 == 0:  # Her dakikada bir log
                        ops.info(f"Görsel üretiliyor... (deneme {attempt}/{self.MAX_POLLS})")
                    continue

                elif state == "success":
                    result_json_str = record.get("resultJson", "")
                    if result_json_str:
                        result_json = json.loads(result_json_str)
                        result_urls = result_json.get("resultUrls", [])
                        if result_urls:
                            image_url = result_urls[0]
                            ops.info(f"Görsel üretimi tamamlandı! URL: {image_url[:80]}...")
                            break

                    ops.error(f"Kie AI success döndü ama URL bulunamadı: {record}")
                    return None

                elif state in ("failed", "fail"):
                    fail_msg = record.get("failMsg", "Bilinmeyen hata")
                    ops.error(f"Kie AI görsel üretimi başarısız: {fail_msg}")
                    return None

                else:
                    ops.warning(f"Bilinmeyen durum: '{state}' (deneme {attempt})")

            except Exception as e:
                ops.error(f"Kie AI polling hatası (deneme {attempt}): {e}", exception=e)

        if not image_url:
            ops.error(f"Kie AI görsel üretimi zaman aşımına uğradı ({self.MAX_POLLS * self.POLL_INTERVAL}s)")
            return None

        # Step 3: Görseli indir
        return self._download_image(image_url)

    def _download_image(self, url: str) -> str:
        """Üretilen görseli indirip geçici dosyaya kaydeder."""
        try:
            resp = requests.get(url, timeout=60)
            resp.raise_for_status()

            content_type = resp.headers.get("Content-Type", "image/png")
            ext = "png" if "png" in content_type else "jpg"

            tmp_file = tempfile.NamedTemporaryFile(
                suffix=f".{ext}",
                prefix="linkedin_img_",
                dir=tempfile.gettempdir(),
                delete=False
            )
            tmp_file.write(resp.content)
            tmp_file.close()

            ops.info(f"Görsel indirildi: {tmp_file.name} ({len(resp.content)} bytes)")
            return tmp_file.name

        except Exception as e:
            ops.error(f"Görsel indirme hatası: {e}", exception=e)
            return None
